import '../analytics/middleware';
import '../authentication/middleware';
import '../av-moderation/middleware';
import '../base/conference/middleware';
import '../base/i18n/middleware';
import '../base/jwt/middleware.any';
import '../base/known-domains/middleware';
import '../base/lastn/middleware';
import '../base/lib-jitsi-meet/middleware';
import '../base/logging/middleware';
import '../base/media/middleware';
import '../base/net-info/middleware';
import '../base/participants/middleware';
import '../base/responsive-ui/middleware';
import '../base/redux/middleware';
import '../base/settings/middleware';
import '../base/sounds/middleware';
import '../base/testing/middleware';
import '../base/tracks/middleware';
import '../base/user-interaction/middleware';
import '../breakout-rooms/middleware';
// DISABLED: import '../calendar-sync/middleware';
import '../chat/middleware';
import '../conference/middleware';
import '../connection-indicator/middleware';
import '../device-selection/middleware';
import '../display-name/middleware';
import '../dynamic-branding/middleware';
// DISABLED: import '../etherpad/middleware';
import '../filmstrip/middleware';
import '../follow-me/middleware';
import '../force-pin/middleware';
import '../invite/middleware';
import '../jaas/middleware';
import '../large-video/middleware';
import '../lobby/middleware';
import '../notifications/middleware';
import '../overlay/middleware';
import '../participants-pane/middleware';
// DISABLED: import '../polls/middleware';
// DISABLED: import '../polls-history/middleware';
// DISABLED: import '../reactions/middleware';
import '../recent-list/middleware';
// DISABLED: import '../recording/middleware';
import '../rejoin/middleware';
import '../room-lock/middleware';
// DISABLED: import '../rtcstats/middleware';
// DISABLED: import '../speaker-stats/middleware';
// DISABLED: import '../subtitles/middleware';
// DISABLED: import '../transcribing/middleware';
import '../video-layout/middleware';
import '../video-quality/middleware';
// DISABLED: import '../videosipgw/middleware';
import '../visitors/middleware';
// DISABLED: import '../whiteboard/middleware.any';

import './middleware';
import '../teacher-presence/middleware';
