import '../base/app/middleware';
import '../base/jwt/middleware.web';
import '../base/config/middleware';
import '../base/connection/middleware';
import '../base/devices/middleware';
import '../base/media/middleware';
import '../deep-linking/middleware.web';
import '../dynamic-branding/middleware';
// DISABLED: import '../e2ee/middleware';
import '../external-api/middleware';
import '../keyboard-shortcuts/middleware';
// DISABLED: import '../no-audio-signal/middleware';
import '../notifications/middleware';
// DISABLED: import '../noise-detection/middleware';
import '../old-client-notification/middleware';
import '../pip/middleware';
// DISABLED: import '../power-monitor/middleware';
import '../prejoin/middleware';
// DISABLED: import '../remote-control/middleware';
import '../screen-share/middleware';
// DISABLED: import '../shared-video/middleware';
// DISABLED: import '../web-hid/middleware';
import '../settings/middleware';
// DISABLED: import '../talk-while-muted/middleware';
import '../toolbox/middleware';
// DISABLED: import '../face-landmarks/middleware';
// DISABLED: import '../gifs/middleware';
// DISABLED: import '../whiteboard/middleware.web';
// DISABLED: import '../file-sharing/middleware.web';
import '../custom-panel/middleware.web';

import './middlewares.any';
